### ISSUE TITLE
How important is the "firehose" problem?

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/observable#12]
A 2019 [attempt at reviving the old TC39 proposal](https://github.com/tc39/proposal-observable/issues/201) involved an API simplification that incidentally allowed Observables to handle the "synchronous firehose of data" problem. That is, it allows a subscriber to unsubscribe (via AbortController, in that proposal) _while_ an Observable is synchronously pushing perhaps a "firehose" of data to the next() handler before `subscribe()` returns (see [this example](https://github.com/tc39/proposal-observable/issues/201#:~:text=Handling%20of%20%22firehose%22%20synchronous%20data)).

My understanding is that neither RxJS nor [zen-observable](https://github.com/zenparsing/zen-observable) currently [support](https://github.com/tc39/proposal-observable/issues/201#issuecomment-542353472) this, but if we're generalizing the API for the platform maybe we should consider it? Designing Observables such that they handle this seems nice, as they can unsubscribe via token based cancelation _in_ the next() handler and even before subscribing is complete if the producer pushes "enough" (or "too much") data.

On the other hand, it could get a little clunky. With this approach, `subscribe()` returns nothing and the assumption is that your only interaction with a "subscription" is via the AbortController that you must create _before_ subscribing. That's not terrible, but it could get worse if we ever wanted to give more functionality to a "subscription" beyond just cancellation. In that world we might need to introduce a `Subscription` object that `subscribe()` returns, but then you'd have two objects to keep track of for any given subscription: the AbortController that you created before calling `subscribe()` and then the `Subscription` returned _from_ `subscribe()`.

That, plus the fact that two major Observable libraries today don't support this (IIUC) might mean there is not enough appetite to cater our design to it. Thoughts?

**Comment by domfarolino** [comment]
I think I _kinda_ follow the example above, but I'm struggling for a few reasons.

 - I imagine you mean `const source = Observable.from([firehose])` instead of `const source = Observable.from(['start'])`? Otherwise `firehose` just doesn't get used.
 - Shouldn't `take()` call `subscriber.next()` sometime?

Even then, when I experiment with it I get an error because `flatten()` accesses `innerSubscription` inside of `innerSource.subscribe`'s complete() handler before `innerSubscription` is actually finished being declared. Also I'm a little confused because I guess nothing seems to be calling `unsubscribe()`? But regardless, I guess the point is that yeah, we're never giving a chance for `unsubscribe()` to run _outside_ of the `next()` handler, so that if the subscription function tries to honestly check `subscription.closed` (like in `firehose`), it doesn't actually matter.

Given all of that, I'm happy we're going the token-based cancellation route and that it would help stop issues in scenarios like this. It sounds like there isn't much actionable here, so shall we close this @benlesh?

**Comment by benlesh** [comment]
> Shouldn't take() call subscriber.next() sometime?

Yes, that was an oversight. I didn't test the code :) I've updated it.

> Also I'm a little confused because I guess nothing seems to be calling unsubscribe()?

When you `complete()` it will teardown. That teardown should include unsubscription of any created subscriptions.

A very important design feature of observable is that teardown will always be called if: 

1. The producer completes.
2. The producer errors.
3. The consumer unsubscribes.

> It sounds like there isn't much actionable here, so shall we close this @benlesh?

Yes we can close this

**Comment by mk-pmb** [comment]
@benlesh I'd like to try and disambiguate some variable names in your example and then try and play around with it. Would you mind releasing it as free software?
Do we have an example implementation of Observables?
Then maybe you could add a test case there that checks whether the current implementation is affected by the problem. (The infinite while loop should probably become a too-far-counting for loop.)

**Comment by domfarolino** [comment]
Just try it out in the chromium implementation under chrome://flags.

**Comment by mk-pmb** [comment]
Update: For the other thread I made an example for how easy it is to release code under the MIT license (see "Example gist" link in my previous post). It would work similar for other free software licenses. So @benlesh if you meant to share your code above for others to learn from it, it would be really nice if you could release it in a way that grants everyone a free software license.

**Comment by benlesh** [comment]
@mk-pmb which code are you speaking of?
