### ISSUE TITLE
`drop` should probably be `skip`.

### ISSUE THREAD

**Issue by benlesh** [domfarolino/observable#24]
I've never seen `skip` called `drop` before. I'm not completely against it, but I do find it odd. Is there a precedent that's being followed there?

**Comment by domfarolino** [comment]
This was initially adopted here to stay consistent with the TC39 iterator helpers proposal: https://tc39.es/proposal-iterator-helpers/#sec-iteratorprototype.drop.

**Comment by benlesh** [comment]
Quite right, I missed that. It's fine.
