### ISSUE TITLE
The constructor doesn't have a way to register teardown. 

### ISSUE THREAD

**Issue by benlesh** [domfarolino/observable#3]
This is pretty critical to the design of Observable. There needs to be some sort of way to register setup and teardown during subscription. In RxJS there's a few paths, but the most well-known/understood one is this:

```ts
new Observable(subscriber => {
  // Setup here
  let n = 0
  const id = setInterval(() => subscriber.next(n++), 1000)
 
  return () => {
    // Teardown here
    clearInterval(id)
  }
})
```

However, if we're leaning on DOM APIs like `AbortSignal` we can use that here as well. It's just admittedly more ugly:

```ts
new Observable(subscriber => {
  // Setup here
  let n = 0
  const id = setInterval(() => subscriber.next(n++), 1000)
 
  subscriber.signal.addEventListener('abort', () => {
    // Teardown here
    clearInterval(id)
  })
})
```

Alternatively, it could come in as the second argument, as it's a very commonly accessed piece of functionality:

```ts
new Observable((subscriber, signal) => {
  // Setup here
  let n = 0
  const id = setInterval(() => subscriber.next(n++), 1000)
 
  signal.addEventListener('abort', () => {
    // Teardown here
    clearInterval(id)
  })
})
```

Finally, the `Subscriber` itself could implement event listener, and that might help clean things up:

```ts
new Observable((subscriber) => {
  // Setup here
  let n = 0
  const id = setInterval(() => subscriber.next(n++), 1000)
 
  subscriber.addEventListener('teardown', () => {
    // Teardown here
    clearInterval(id)
  })
})
```

I prefer something like the fourth option, because one of the guarantees observable is supposed to provide is that when you `error()` or `complete()` or `unsubscribe()`, the teardown is called. `"abort"` is maybe a misnomer.

**Comment by robbiespeed** [comment]
I'd like to make a suggestion that's similar to passing the abort signal, but adds greater flexibility.
```
const o = new Observable((subscriber, registerTeardown) => {
  // Setup here
  let n = 0
  const id = setInterval(() => subscriber.next(n++), 1000)
 
  registerTeardown?.(() => {
    // Teardown here
    clearInterval(id)
  })
});
```
This allows teardown to be triggered by a AbortController, Observable, Promise, (pretty much anything):
```
o.subscribe(console.log, (dispose) =>
  abortSignal.addEventListener('abort', dispose, { once: true })
);
o.subscribe(console.log, (dispose) => otherObservable.subscribe(dispose));
o.subscribe(console.log, (dispose) => promise.then(dispose));
```
