### ISSUE TITLE
Status of this Proposal

### ISSUE THREAD

**Issue by codesculpture** [domfarolino/observable#46]
Can anyone say this proposal's status, please?

**Comment by domfarolino** [comment]
Thanks for asking! I've been trying to wrap up a few things before diving full-time into this proposal, but it's still indeed active if that's what you're asking. We're planning on discussing this [at TPAC 2023](https://github.com/whatwg/meta/issues/284) in Spain as well, and I hope to send a Chromium [Intent to Prototype](https://www.chromium.org/blink/launching-features/#prototyping) at some point. I expect to be more active on this proposal quite soon, so I think I'll close this issue for now.

Also there's a very rough (and slightly outdated) [Chromium prototype](https://chromium-review.googlesource.com/c/chromium/src/+/4262153) of a subset of this proposal that I'll be iterating on in the near future as well!

**Comment by ljharb** [comment]
@domfarolino i still really hope it can be brought to TC39.
