### ISSUE TITLE
Be careful not to over-claim in "Userland libraries"

### ISSUE THREAD

**Issue by domenic** [domfarolino/observable#8]
I believe several of the "observable" implementations listed, don't conform to the [observable contract](https://reactivex.io/documentation/contract.html) referenced. It would be good to separate out the ones that do, from the ones that are vaguely in a similar conceptual area. The former give support directly to the proposed design in the explainer; the latter just tell us that this is a problem area worth solving, but perhaps with a completely different API.

**Comment by benlesh** [comment]
Here's PR to address this: https://github.com/domfarolino/observable/pull/23

(I forgot to put the issue # in the commit messages, sorry).

**Comment by domfarolino** [comment]
@benlesh Thanks a lot for the PR. Do you think we're OK to close this given your updated prose?

**Comment by benlesh** [comment]
Yeah.
